### ISSUE TITLE
Checkbox group seem to be bugged

### ISSUE THREAD

**Issue by Ebonkaiser** [adfinis/ember-validated-form#1080]
Using the examples from the documentation website, I managed to style with bootstrap and get most of the form to render. However, it seems to stop at the "notifications"checkbox and gives me this error in the console.

Attempted to resolve `includes`, which was expected to be a helper, but nothing was found.

i got a similar error with ColorComponent from the "favorite-colors" file. It says that color-component is expected to be  component but nothing was found as well. 

Thanks

**Comment by derrabauke** [comment]
Hey @Ebonkaiser, 

could you try adding `ember-composable-helpers` to your app and try again? I think we are missing this dependency.

**Comment by Ebonkaiser** [comment]
That works for the checkbox group! Thanks!

Now the color-component issue still remains.

Same sort of deal, 

"Attempted to resolve `color-component`, which was expected to be a component, but nothing was found."

It looks like it's having trouble with the <ColorComponent> in the favorite-colors class

**Comment by derrabauke** [comment]
The `ColorComponent` is only an example of a custom component you could use inside the `ValidatedInput`. It's part of [the test/dummy app](https://github.com/adfinis/ember-validated-form/tree/main/tests/dummy/app/components) but not included in the addon exports. So you would have to copy the `ColorComponent` to your apps `components` folder to make it available.
