### ISSUE TITLE
Ember 5.5 Form is not actually validating

### ISSUE THREAD

**Issue by Ebonkaiser** [adfinis/ember-validated-form#1081]
Upon using the latest validator and ember packages, it appears as though the form doesn't actually validate. No errors present.

Please advise

**Comment by derrabauke** [comment]
Could you give us a little bit more concrete information or in the best case a reproduction repo?

Saying `latest` is a relative statement , which could be *not the latest* already today.

ember version: 5.5
ember-validated-form: ?

You could also clone this repo and link it to you app locally (via [`pnpm link`](https://pnpm.io/cli/link)) and set a debugger to [this line](https://github.com/adfinis/ember-validated-form/blob/167c811b7957a5d7776599e9c5ad0fe0c05edf85/addon/components/validated-form.js#L45).

**Comment by Ebonkaiser** [comment]
Ember version: 5.5
ember-validated-form: 7.0

I will try the debugger if all else fails. Right now it shows all fields, although empty, as valid. 

to reiterate, I'm following your example exactly.

**Comment by chepworth** [comment]
Ember version: 4.12
ember-validated-form: 7.0.1

Using ember-cp-validations 6.0.1 which is working correctly but no validate errors show on screen.

// sign-in.js component
import Component from '@ember/component';
import { getOwner } from '@ember/application';
import EmberObject, { set } from '@ember/object';
import FormMixin from 'branz-artizan-web/mixins/forms/form-mixin';
import { task } from 'ember-concurrency';
import { validator, buildValidations } from 'ember-cp-validations';

const FormModel = EmberObject.extend(buildValidations({
  email: {
    description: 'Email',
    validators: [
      validator('presence', true),
    ]
  }
}));

export default Component.extend(FormMixin, {
  init() {
    this._super(...arguments);

    const ownerInjection = getOwner(this).ownerInjection();
    set(this, 'formModel', FormModel.create(ownerInjection));
  },

  taskSubmitForm: task(function* (model) {
    try {
      yield model.validate(); // Validate the form
      if (model.get('validations.isValid')) {
        // Form is valid, proceed with form submission
        console.log('Form is valid');
      } else {
        // Form is invalid, handle validation errors
        console.log('Form is invalid');
      }
    } catch (error) {
      // Handle validation error
      console.error('Form validation error:', error);
    }
  }).drop(),

});

// sign-in.hbs component

<ValidatedForm @model={{changeset this.formModel}}
  class="Form--fixedWidth"
  @validateBeforeSubmit={{true}}
  @on-submit={{perform this.taskSubmitForm this.formModel}} as |f|>

  <f.input
    @name="email"
    @type="email"
    @label="email"
    @placeholder="example@email.com"
    @validateBeforeSubmit={{true}}
    @required={{true}}/>

  {{#if f.errors.email.isValid}}
    <div class="Alert Alert--error">{{f.errors.email.message}}</div>
  {{/if}}

  {{#if f.touched.email}}
    {{#unless f.validations.attrs.email.isValid}}
      <div class="Alert Alert--error">{{f.validations.attrs.email.message}}</div>
    {{/unless}}
  {{/if}}

  {{#let f.submit as |Submit|}}
    <Submit @label={{if f.loading 'Saving...' 'Save'}} @disabled={{f.loading}}/>
  {{/let}}

</ValidatedForm>

**Comment by derrabauke** [comment]
@chepworth This addon is based on `ember-changese-validations`. I don't know about the API nor the compatibility of `ember-cp-validations`.

**Comment by chepworth** [comment]
@derrabauke I suspect the problem is also evident with ember-changeset-validations as the original ticket was raised by EbonKaiser
