### ISSUE TITLE
Docs are busted

### ISSUE THREAD

**Issue by brandensilva** [adfinis/ember-validated-form#843]
When visiting https://docs.adfinis.com/ember-validated-form/ you just get a 404 message. When visiting docs.adfinis.com directly, you are presented with a nice "Hello World" message.

**Comment by HugoJF** [comment]
Docs can be directly accessed [here](https://adfinis.github.io/ember-validated-form/docs).

**Comment by brandensilva** [comment]
Thanks, it looks like they have been restored! Closing out the issue.
